### ISSUE TITLE
[11.0][BUG] hr_timesheet_sheet: unable to remove all lines of a timesheet sheet

### ISSUE THREAD

**Issue by astirpe** [OCA/timesheet#198]
Reproduced in Runbot:

 - Create some lines in the details tab. Save.
 - Click on Edit.
 - In the details tab, remove the lines one by one (click on the trash bin icon).

When attempting to remove the last line, all the previously deleted lines reappear again.

**Comment by MiquelRForgeFlow** [comment]
FYI, your description is a bit inaccurate. When you are deleting the analytic lines by an order (from the first to the last, or from the last to the first), the error is not produced. The error only is produced if you delete the lines randomly without any order.

After checking this issue, I can say that this issue is in the wrong place. By what I observed, I think it's an Odoo error in managing one2many lists. My two cents is in the javascript files in web module, related to some sorting of the elements of the lists. I cannot provide the fix because I am very bad in javascript.

**Comment by astirpe** [comment]
To me it seems happening in every case. Doesn't matters in which order I'm deleting lines.

**Comment by MiquelRForgeFlow** [comment]
Proof:

![gifrecord_2019-03-06_150939](https://user-images.githubusercontent.com/25005517/53887238-29735200-4022-11e9-84f7-7de5e492afbf.gif)
