### ISSUE TITLE
[RFC] Timesheet Activity Types 

### ISSUE THREAD

**Issue by dreispt** [OCA/timesheet#354]
Module name: hr_timesheet_activity_type
Dependency: hr_timesheet, project
License: AGPL-3

Adds an Activity Type column to Timesheet lines, to be allow better categorization of the time spent.
For example, "Internal Meeting", "Design", "Development", "Tests".
Note that this is a different concept from Roles in Timesheet Roles (hr_timesheet_role).

**Comment by alexey-pelykh** [comment]
We've considered such an approach sometime ago, yet came to conclusion that such separation should (in our case) be done as Jira Epic and corresponding tasks, or as a different stages + tasks. Out of pure curiosity, what's the justification in your case?

**Comment by dreispt** [comment]
For analysis and reporting purposes. for example, I want to be able to report "Client Meetings" time, or time spent with "Tests".

**Comment by alexey-pelykh** [comment]
In no way I want to interfere with the RFC, yet just sharing what we came up with (as we're service business): that testing of a feature should be recorded as a separate Task, linked to a Story (that describes the feature), while Client Meetings ("Communication" in our Jira) is a separate task type, that is rarely bindable on 1-1 basis to a specific feature.

In a product-style setup, this would've been "time spent in Testing status" (using jira) + Client Meetings ("Communication" in our Jira) is a separate task, since rarely it's possible to force customer to keep discussion only about 1 task/feature/etc.

**Comment by dreispt** [comment]
Of course comments are welcome - it's an RFC 😉 

What you describe could be done with subtasks in Odoo.
It could work, but it will create a lot of additional data entering effort, to create all the needed subtasks for each Feature/Task.
These Activity Types are sometimes close to a Stage, sometimes close to a Subtask, or even to a Role.

I stopped to considering that approach, but it feel that just adding an Activity Type could be a simpler starting point.

Thanks for the insights!
